"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { NeynarContextProvider, Theme } from "@neynar/react";
import "@neynar/react/dist/style.css";
import { AppProvider } from "./Context/AppContext";
import NeynarProviderWrapper from "./Context/NeynarProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <AppProvider>
          <NeynarProviderWrapper>
            <Header />
              {children}
            <Footer />
          </NeynarProviderWrapper>
        </AppProvider>
      </body>      
      
    </html>    
  );
}
